"""init_db

Revision ID: 97bb0aeac95d
Revises: 8f096db25445
Create Date: 2024-02-23 18:22:09.212420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bb0aeac95d'
down_revision: Union[str, None] = '8f096db25445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atleta', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint('atleta_centroTreinamento_id_fkey', 'atleta', type_='foreignkey')
    op.create_foreign_key(None, 'atleta', 'centro_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atleta', 'centroTreinamento_id')
    op.add_column('centro_treinamento', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centro_treinamento', 'created_at')
    op.add_column('atleta', sa.Column('centroTreinamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atleta', type_='foreignkey')
    op.create_foreign_key('atleta_centroTreinamento_id_fkey', 'atleta', 'centro_treinamento', ['centroTreinamento_id'], ['pk_id'])
    op.drop_column('atleta', 'centro_treinamento_id')
    # ### end Alembic commands ###
